name: 'Build DEB package on buster'
description: 'Build a Debian package, using the latest version of Debian Buster'
outputs:
  filename:
    description: 'Name of the built `.deb` file'
  filename-dbgsym:
    description: 'Name of the built `.deb` file for debug symbols'

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: gray-dark
