#!/bin/sh -e

#DEBHELPER#

case "$1" in
	purge)
		rm -rf /var/lib/portmaster
		;;
	remove)
		rm -rf /var/lib/portmaster/updates
		;;
	upgrade)
		# We don't want to remove anything in the upgrade
		# phase.
		;;
esac